name: testing a workflow

on:
    workflow_run:
        workflows: ["ESLint"]
        types:
            - completed
        branches:
            - main

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
  
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: echo "Hello World"
                

    frontend-test:
        needs: [eslint]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: |
                cd frontend
                npm ci

            - name: Start frontend server
              run: |
                cd frontend
                npm start &
                sleep 10

    backend-test:
        needs: [eslint]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
  
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: |
                cd backend
                npm ci

            - name: Start backend server
              run: |
                cd backend
                npm run start
    

    deploy:
        needs: [eslint, frontend-test, backend-test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
  
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'



    









